// game action types
export const SHUFFLE_CARDS = '@GAME/SHUFFLE_CARDS';
export const START_GAME = '@GAME/START_GAME';
export const SET_CARDS = '@GAME/SET_CARDS'; // document
export const PICK_FIRST_CARD = '@GAME/PICK_FIRST_CARD';
export const PICK_SECOND_CARD = '@GAME/PICK_SECOND_CARD';
export const SET_FIRST_CARD = '@GAME/SET_FIRST_CARD'; // document
export const SET_SECOND_CARD = '@GAME/SET_SECOND_CARD'; // document
export const CARDS_MATCH = '@GAME/CARDS_MATCH';
export const SET_MATCHED_CARDS = '@GAME/SET_MATCHED_CARDS'; // document
export const CARDS_NOT_MATCH = '@GAME/CARDS_NOT_MATCH';
export const GAME_ENDED = '@GAME/GAME_ENDED';
export const STEPS_RESET = '@GAME/STEPS_RESET';
export const SET_STEPS = '@GAME/SET_STEPS'; // document
export const STEPS_INCREMENT = '@GAME/STEPS_INCREMENT';
export const SET_TIMER = '@GAME/SET_TIMER'; // document
export const TIMER_RESET = '@GAME/TIMER_RESET';
export const TIMER_START = '@GAME/TIMER_START';
export const TIMER_INCREMENT = '@GAME/TIMER_INCREMENT';
export const TIMER_STOP = '@GAME/TIMER_STOP';